// Copyright (C) 2021  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 21.1 (Build Build 842 10/21/2021)
// Created on Mon Aug 15 17:22:03 2022

fire_trigger fire_trigger_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.btn(btn_sig) ,	// input  btn_sig
	.fire(fire_sig) ,	// output  fire_sig
	.rst(rst_sig) ,	// input  rst_sig
	.enb(enb_sig) 	// input  enb_sig
);

defparam fire_trigger_inst.WAIT = 'b0;
defparam fire_trigger_inst.COUNT = 'b1;
